### ISSUE TITLE
Failed to copy jails.yml

### ISSUE THREAD

**Issue by barkawa** [timbru31/PasswordProtect#53]
### What steps will reproduce the problem?
Install PasswordProtect -> Restart

### Expected output
jails.yml is created, or if it's not necessary no exceptions are thrown.

### What do you see instead?
see log

### Log file of the issue/error
<details>
  <summary>Log</summary>

  ```
07.05 04:23:18 [Server] INFO Enabling PasswordProtect v3.1.0
07.05 04:23:18 [Server] WARN Failed to copy the default config!
07.05 04:23:18 [Server] INFO java.nio.file.NoSuchFileException: plugins/PasswordProtect/jails.yml
07.05 04:23:18 [Server] INFO at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
07.05 04:23:18 [Server] INFO at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
07.05 04:23:18 [Server] INFO at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
07.05 04:23:18 [Server] INFO at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
07.05 04:23:18 [Server] INFO at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
07.05 04:23:18 [Server] INFO at java.nio.file.Files.newOutputStream(Files.java:220) ~[?:?]
07.05 04:23:18 [Server] INFO at de.dustplanet.passwordprotect.utils.PasswordProtectUtilities.copy(PasswordProtectUtilities.java:72) ~[?:?]
07.05 04:23:18 [Server] INFO at de.dustplanet.passwordprotect.PasswordProtect.onEnable(PasswordProtect.java:81) ~[?:?]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
07.05 04:23:18 [Server] ERROR Cannot load plugins/PasswordProtect/jails.yml
07.05 04:23:18 [Server] INFO java.io.FileNotFoundException: plugins/PasswordProtect/jails.yml (No such file or directory)
07.05 04:23:18 [Server] INFO at java.io.FileInputStream.open0(Native Method) ~[?:?]
07.05 04:23:18 [Server] INFO at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
07.05 04:23:18 [Server] INFO at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
07.05 04:23:18 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at de.dustplanet.passwordprotect.utils.ScalarYamlConfiguration.loadConfiguration(ScalarYamlConfiguration.java:46) ~[?:?]
07.05 04:23:18 [Server] INFO at de.dustplanet.passwordprotect.PasswordProtect.onEnable(PasswordProtect.java:83) ~[?:?]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-648]
07.05 04:23:18 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
  ```
</details>

### /version output?
Paper version git-Paper-648 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### PasswordProtect version
3.1.0

### Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid PasswordProtect version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Weird. Did this work before upgrading Paper?

**Comment by barkawa** [comment]
This was the first time I used the plugin, but I could try with another Paper version if needed. Also the exception was only thrown on first launch, after a restart it worked fine and jails.yml exists now.
